name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi friend! Thanks for creating your first issue in this repo. Feel free to create more issues if there anything unclear'
        pr-message: 'Hi friend! Thanks for your first contribution on this repo.'
